### ISSUE TITLE
hugo 发布时，生成的 .md 文件名问题

### ISSUE THREAD

**Issue by zwyyy456** [terwer/siyuan-plugin-publisher#1530]
通过 hugo 发布时，添加到 github 的 .md 文件，能否有 yaml 中 slug 的内容来决定，例如 slug 的内容为 `test-hugo.zh`，则生成 `test-hugo.zh.md`，现在无法修改添加到 GitHub 仓库的 md 文件的文件名。

**Comment by terwer** [comment]
暂时不支持。
因为发布工具是自动的，不能检测到是否重名。如果允许修改会导致重名的情况。暂时只能配置为固定的规则。看这里：
https://github.com/terwer/siyuan-plugin-publisher/issues/1495#issuecomment-2510514315

**Comment by terwer** [comment]
我看看考虑支持加上你这个自动读取 yaml的功能，通过配置开启，但是要自己控制是否重名了。重名会发布失败

![image](https://github.com/user-attachments/assets/998d6059-61fd-46df-8eb8-5bdeaa84d95f)

![image](https://github.com/user-attachments/assets/7a6f6877-a151-43f7-9b68-59f81b9a1ac8)

![image](https://github.com/user-attachments/assets/3380d16c-9363-4b36-a742-121bc52f9a08)

![image](https://github.com/user-attachments/assets/ab662f21-ae02-4b2d-95b5-7e8b2749f59c)


![image](https://github.com/user-attachments/assets/91087786-499d-4a89-a09f-9441118302a5)


fixed in `v1.30.2`

**Comment by zwyyy456** [comment]
ok，感谢
